export const CREATE_TASK_REQUEST='CREATE_TASK_REQUEST';
export const CREATE_TASK_SUCCESS='CREATE_TASK_SUCCESS';
export const CREATE_TASK_FAIL='CREATE_TASK_FAIL';

export const EDIT_TASK_REQUEST='EDIT_TASK_REQUEST';
export const EDIT_TASK_SUCCESS='EDIT_TASK_SUCCESS';
export const EDIT_TASK_FAIL='EDIT_TASK_FAIL';

export const DELETE_TASK_FAIL='DELETE_TASK_FAIL';
export const DELETE_TASK_REQUEST='DELETE_TASK_REQUEST';
export const DELETE_TASK_SUCCESS='DELETE_TASK_SUCCESS';


export const CLEAR_ERRORS='CLEAR_ERRORS';